# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=1, verbose_name='性別')),
                ('hire_date', models.DateField(verbose_name='雇用日')),
            ],
            options={
                'verbose_name': '社員',
                'verbose_name_plural': '社員',
                'db_table': 'yo_employees',
            },
        ),
    ]
