# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=50, verbose_name='案件名')),
                ('case_place', models.CharField(max_length=50, verbose_name='案件場所')),
                ('case_start_time', models.DateField(verbose_name='案件開始時間')),
                ('case_end_time', models.DateField(verbose_name='案件終了時間')),
                ('case_belongings', models.CharField(choices=[('J', '自社'), ('T', '他社'), ('U', '未知')], default='U', max_length=1, verbose_name='案件所属')),
                ('case_industry', models.CharField(blank=True, max_length=20, null=True, verbose_name='作業場所')),
                ('case_language', models.CharField(blank=True, max_length=20, null=True, verbose_name='言語')),
                ('case_price', models.CharField(max_length=10, verbose_name='単価')),
                ('case_remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': 'a',
                'verbose_name_plural': 'b',
                'db_table': 'yo_Case',
            },
        ),
    ]
