# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.BigIntegerField(blank=True, null=True, verbose_name='工资')),
                ('present_flg', models.CharField(default='0', max_length=1, verbose_name='现在适用')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='适用开始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='适用终了日')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
            options={
                'verbose_name': '社員工资',
                'verbose_name_plural': '社員工资',
                'db_table': 'yo_employee_salary',
            },
        ),
    ]
