# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_case'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
