# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_careerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='技術')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
            options={
                'verbose_name': '技術',
                'verbose_name_plural': '技術',
                'db_table': 'yo_technology',
            },
        ),
        migrations.AddField(
            model_name='careerhistory',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
            preserve_default=False,
        ),
    ]
