# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20180617_1227'),
        ('employees', '0003_salary'),
    ]

    operations = [
    ]
